version: '3.8'

services:

  # The PostgreSQL database service
  postgres_db:
    image: postgres:15.14-bookworm
    container_name: postgres_db
    environment:
      POSTGRES_DB: human-resource
      POSTGRES_USER: human-resource
      POSTGRES_PASSWORD: human-resource
      networks: human-resource-network
    ports:
      - "5432:5432"
    volumes:
      - human-resource-db:/var/lib/postgresql/data
  # The Spring Boot application service
  human_resource_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: human_resource-app:v1
    ports:
      - "8090:8090"

    environment:
      # Database connection environment variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/human-resource
      SPRING_DATASOURCE_USERNAME: human-resource
      SPRING_DATASOURCE_PASSWORD: human-resource

      # Set the application's port to 8090 within the container
      SERVER_PORT: 8090

      # Optional: Add JPA/Hibernate configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      depends_on:
        postgres_db
      #          condition: service_healthy  # Ensure the database is healthy

      networks: human-resource-network

networks:
  human-resource-network:
    driver: bridge

volumes:
  human-resource-db: