spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/human-resource
    username: human-resource
    password: human-resource
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never   # ensures schema.sql and data.sql run on startup
      continue-on-error: true

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    caches: employees,grades