spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/human-resource
    username: human-resource
    password: human-resource
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      continue-on-error: true

  redis:
    host: redis
    port: 6379
    caches: employees,grades